name: export

on:
  schedule:
    - cron: "0 3 * * 3"
  workflow_call:
    secrets:
      COMMON_VOICE_BRANCH:
        required: true
      COMMON_VOICE_ORG:
        required: true
      COMMON_VOICE_REPO:
        required: true
      GH_KEY:
        required: true
      GH_USERNAME:
        required: true
      SC_EXPORT_BASE_URL:
        required: true

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Clone CV
        run: git clone --depth 1 https://${{secrets.GH_USERNAME}}:${{secrets.GH_KEY}}@github.com/${{secrets.COMMON_VOICE_ORG}}/${{secrets.COMMON_VOICE_REPO}} cv
      - name: Checkout CV
        run: cd cv && git checkout ${{secrets.COMMON_VOICE_BRANCH}}
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16
      - name: Install SC dependencies
        run: npm ci

      - name: Set Git Author
        run: git config --global user.name "Sentence Collector Exporter"
      - name: Set Git Email
        run: git config --global user.email "mkohler+cvexport@picobudget.com"

      - name: Run Export
        run: env API_BASE_URL=${{secrets.SC_EXPORT_BASE_URL}} COMMON_VOICE_PATH=cv/ node scripts/exporter.js
      - name: CV Changes
        run: cd cv && git diff --numstat
      - name: Format Changes
        run: cd cv && git add -A && npx pretty-quick --staged
      - name: Commit CV Changes
        run: cd cv && git commit -m "Automatic Sentence Collector Export + Update Locales if necessary"

      - name: Prepare locale FTL source file (EN)
        run: env COMMON_VOICE_PATH=cv/ node scripts/export-source-strings.js
      - name: Add CV Changes
        run: cd cv && git add web/locales/en/messages.ftl || true
      - name: Commit CV Changes
        run: cd cv && git commit -m "Export Sentence Collector source strings" || true

      - name: Push to CV
        run: cd cv && git push origin ${{secrets.COMMON_VOICE_BRANCH}}
