name: export

on:
  schedule:
    - cron: "30 15 * * 5"

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Clone CV
        run: git clone --depth 1 https://${{secrets.GH_USERNAME}}:${{secrets.GH_KEY}}@github.com/${{secrets.COMMON_VOICE_ORG}}/${{secrets.COMMON_VOICE_REPO}} cv
      - name: Checkout CV
        run: cd cv && git checkout ${{secrets.COMMON_VOICE_BRANCH}}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install CV dependencies (npm is good enough)
        run: cd cv && NODE_ENV=development npm install && rm package-lock.json
      - name: Install SC dependencies
        run: npm ci
      - name: Run Export
        run: env API_BASE_URL=${{secrets.SC_EXPORT_BASE_URL}} COMMON_VOICE_PATH=cv/ node scripts/exporter.js
      - name: Run CV Update Locales Script
        run: cd cv && npm run import-locales
      - name: CV Changes
        run: cd cv && git diff --numstat
      - name: Set Git Author
        run: git config --global user.name "Sentence Collector Exporter"
      - name: Set Git Email
        run: git config --global user.email "mkohler+cvexport@picobudget.com"
      - name: Format Changes
        run: cd cv && git add -A && npx pretty-quick --staged
      - name: Commit CV Changes
        run: cd cv && git commit -m "Automatic Sentence Collector Export + Update Locales if necessary"
      - name: Push to CV
        run: cd cv && git push origin ${{secrets.COMMON_VOICE_BRANCH}}

